### ISSUE TITLE
Missing Yokozuna tests

### ISSUE THREAD

**Issue by coderoshi** [basho/giddyup#108]
These yokozuna tests don't appear in giddyup:
- yz_dt_test
- yz_monitor_solr
- yz_security
- yz_stat_test

And these tests no longer exist in the test suite:
- yz_flag_transitions

**Comment by seancribbs** [comment]
Fixed and deployed, thanks!

**Comment by rzezeski** [comment]
The migration test needs to be renamed.

`yz_rs_migration` to `yz_rs_migration_test`.

I started to do the work myself but then realized I don't have ruby & bundler installed to generate the migration bits. @seancribbs, I figure this would take you a couple of minutes so I thought why waste time getting caremad with ruby.

**Comment by seancribbs** [comment]
@rzezeski Fixed and deployed :santa:

**Comment by rzezeski** [comment]
You da man. Thx.

**Comment by seancribbs** [comment]
Happy holidays, have a taste

On Wed, Dec 25, 2013 at 8:50 PM, Ryan Zezeski notifications@github.comwrote:

> You da man. Thx.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/basho/giddyup/issues/108#issuecomment-31209632
> .

## 

Sean Cribbs sean@basho.com
Software Engineer
Basho Technologies, Inc.
http://basho.com/
