### ISSUE TITLE
Where is repl_rt_ack?

### ISSUE THREAD

**Issue by cmeiklejohn** [basho/giddyup#115]
When was this added?  Should it be here?  I can't find the test in riak_test?

**Comment by cmeiklejohn** [comment]
@seancribbs I can't find any trace of this test, and it's been failing since at least pre6, so can we just remove this from GiddyUp 2.0 going forward?

**Comment by seancribbs** [comment]
Consider it done.

**Comment by seancribbs** [comment]
Deployed
