### ISSUE TITLE
Add ensemble tests to giddyup

### ISSUE THREAD

**Issue by kellymclaughlin** [basho/giddyup#127]
The riak ensemble tests are:
- ensemble_basic.erl  
- ensemble_basic2.erl
- ensemble_basic3.erl 
- ensemble_basic4.erl
- ensemble_interleave.erl
- ensemble_sync.erl

All backends, no upgrades, 2.0+ only

**Comment by seancribbs** [comment]
When you say "all backends", do they need to test _every_ backend or does the backend not matter?

**Comment by kellymclaughlin** [comment]
Sorry for that confusion. I think it is the latter, it doesn't matter which so the default is fine.

**Comment by seancribbs** [comment]
Deployed
