### ISSUE TITLE
Remove riak_control_upgrade.

### ISSUE THREAD

**Issue by cmeiklejohn** [basho/giddyup#130]
Remove the obsolete riak_control_upgrade test from 2.0+.

**Comment by cmeiklejohn** [comment]
@seancribbs What's the correct way to do this?

**Comment by seancribbs** [comment]
I'll get it this afternoon if possible. The gist is:
1. Make a migration to change the max_version on existing test records.
2. Update seed to do the same.

**Comment by seancribbs** [comment]
Deployed.
