### ISSUE TITLE
Add ensemble_byzantine

### ISSUE THREAD

**Issue by andrewjstone** [basho/giddyup#138]
PR not yet merged
https://github.com/basho/riak_test/pull/666

**Comment by seancribbs** [comment]
@andrewjstone Obviously no upgrades & requires 2.0, but are there any backend requirements? Should it test all backends?

**Comment by andrewjstone** [comment]
@seancribbs Right now this test only supports bitcask. It could be made to work with any file based backend, but currently the use of "bitcask" in the data path is hardcoded. I don't however think it really matters which backend is used for this particular test, as long as it stores data files and isn't all in memory.

**Comment by seancribbs** [comment]
Resolved in d09ae4d.

**Comment by seancribbs** [comment]
Deployed.
