### ISSUE TITLE
Please add some repl tests to 1.4

### ISSUE THREAD

**Issue by engelsanchez** [basho/giddyup#143]
I am not sure anymore how to do it myself anymore. I see this one PR that added SQL statements to add a test: https://github.com/basho/giddyup/pull/142/files

I can give it a try if you give me some pointers.

Basically I would like to have a number of repl tests that are not in the 1.4 run, and would love to have them when 1.4.12 is out in the next few days:
- repl_aae_fullsync
- repl_aae_fullsync_custom_n
- replication2_rt_sink_connection

Thanks!

**Comment by seancribbs** [comment]
@engelsanchez I see [`repl_aae_fullsync`](http://giddyup.basho.com/#/projects/riak_ee/scorecards/101/101-1668-repl_aae_fullsync-centos-6-64) and [`replication2_rt_sink_connection`](http://giddyup.basho.com/#/projects/riak_ee/scorecards/101/101-1597-replication2_rt_sink_connection-centos-6-64) in the 1.4.x scorecard.  `repl_aae_fullsync_custom_n` seems to have a `min_version` of `2.0.0`.

**Comment by seancribbs** [comment]
Ohhhhhhhh. This is a silly bug. It amounts to `"1.4.4" < "1.4.10" == false`. I'll have to think of a better fix.
