### ISSUE TITLE
Test flakiness tracker (wacky idea)

### ISSUE THREAD

**Issue by slfritchie** [basho/giddyup#45]
Hiya.  This wacky idea comes via @kuenishi who'd suggested looking at the doc http://www.chromium.org/developers/how-tos/webkit-gardening for ideas about how a source code "gardener" can be successful.

Part of that doc mentions the "Flakiness Dashboard"
- Dashboard: http://test-results.appspot.com/dashboards/flakiness_dashboard.html#useWebKitCanary=true
- Dashboard docs: http://dev.chromium.org/developers/testing/flakiness-dashboard

**Comment by seancribbs** [comment]
@slfritchie Are there known, straightforward algorithms for qualifying "flakey" tests? Seems like it should be a classic algorithm to detect streaks or alternations.

**Comment by slfritchie** [comment]
I haven't looked at their code to see if they have an algorithm for flakiness -> hard boolean value.  I just looked at a snapshot of the Web UI to see the rows of test A with one color pattern of success/failure and rows of test B, C, et al. with different patterns.  {shrug}  Seems like a very useful idea: if I'm not familiar with a test, and it's failing for me now, how far back do I need to go for a passing test?  Has it flipflopped (visual or algorithmic determination) lately?

If the idea is too wacky or too difficult to do, that's fine.  I just thought I'd point it out because it's the first time I'd seen something like it and thought it might be novel to others also.

**Comment by seancribbs** [comment]
See also #83

**Comment by seancribbs** [comment]
Unless we're looking for additional flakiness information (i.e. aggregate across releases/platforms, etc), I think #83 has addressed this issue enough for our current use.
