### ISSUE TITLE
Add mapred_* tests

### ISSUE THREAD

**Issue by beerriot** [basho/giddyup#53]
Please add the following tests to the matrix: `mapred_basic_compat`, `mapred_buffer_prereduce`, `mapred_dead_pipe`, `mapred_javascript`, `mapred_notfound_failover`.

All tests except `mapred_notfound_failover` shouldn't care what backend they run against. The `mapred_notfound_failover` test _must_ be run against the memory backend, because it relies on the ability to clear a vnode's storage by killing the vnode process (to force a notfound).

All tests should be fine to run in mixed-version environments, but none should be expected to survive a rolling upgrade, because MR doesn't do that.

**Comment by seancribbs** [comment]
Thank you @beerriot, as always you are a gentleman and a scholar.
