### ISSUE TITLE
Once merged, add support for tests/replication2_pg.er

### ISSUE THREAD

**Issue by bookshelfdave** [basho/giddyup#59]
https://github.com/basho/riak_test/pull/244
- "bitcask", "eleveldb", and "memory" backends
- any platform
- since Riak 1.2
- Riak EE only

**Comment by seancribbs** [comment]
@metadave Does this mean you need to test it against all backends, or do they not matter?

**Comment by bookshelfdave** [comment]
Backend doesn't matter. Thanks Sean!

**Comment by bookshelfdave** [comment]
An update to this issue:
The following tests need to be run from the replication2_pg module via the `riak_test -t m:f` param
test_basic_pg_mode_repl13,
test_basic_pg_mode_mixed,
test_12_pg_mode_repl12,
test_12_pg_mode_repl_mixed,
test_mixed_pg,
test_multiple_sink_pg,
test_bidirectional_pg,
test_pg_proxy
