### ISSUE TITLE
Once merged, add support for tests/replication2_fsschedule.erl

### ISSUE THREAD

**Issue by bookshelfdave** [basho/giddyup#60]
https://github.com/basho/riak_test/pull/221
- "bitcask", "eleveldb", and "memory" backends
- any platform
- 1.4
- Riak + Riak EE

**Comment by seancribbs** [comment]
@metadave Same question as #59, does this mean you need to test it against all backends, or do they not matter?

**Comment by bookshelfdave** [comment]
Backend doesn't matter.

**Comment by bookshelfdave** [comment]
Fullsync test merged:
https://github.com/basho/riak_test/pull/221
