### ISSUE TITLE
add verify_dynamic_ring

### ISSUE THREAD

**Issue by jrwest** [basho/giddyup#70]
backend: bolth
1.4 min vsn.

commit: https://github.com/basho/riak_test/commit/df75db3a0005add0cd4274d2b51f32c42b58ae24

**Comment by seancribbs** [comment]
@jrwest Does the backend matter, i.e. is there potential for one to fail while another passes?

**Comment by jrwest** [comment]
@seancribbs I wanted to do both for some extra testing since it is possible one backend reacts differently than the other (although unlikely). however, the test is a bit long so if you prefer I have no objection to "doesn't matter"
