### ISSUE TITLE
Please add the new 2i tests to giddyup

### ISSUE THREAD

**Issue by russelldb** [basho/giddyup#71]
The tests are:-

verify_2i_stream
verify_2i_limit
verify_2i_returnterms
verify_cs_bucket

Many thanks!

**Comment by seancribbs** [comment]
@russelldb Backends? Just leveldb or also memory? Are both supported?

**Comment by russelldb** [comment]
oops :blush: level and memory please.

**Comment by seancribbs** [comment]
Merged/closed.

**Comment by seancribbs** [comment]
ping for kanban
