### ISSUE TITLE
Pleases add verify_handoff_mixed

### ISSUE THREAD

**Issue by beerriot** [basho/giddyup#92]
The `verify_handoff_mixed` test from basho/riak_test#400 should be added to all 2.0 (and future) runs.

It operates somewhat like `loaded_upgrade`, in that it also uses either a `previous` or a `legacy` version node, according to the `upgrade_version` metadata. It would be great to have the test run twice, once with `upgrade_version=previous` and once `=legacy`.

I'll warn that the test often takes four minutes to run successfully, and will take over five minutes to fail. It has to wait for handoff to finish, and that can take a while. Raising `handoff_concurrency` to 8 did not reduce the success time.

**Comment by seancribbs** [comment]
Did you decrease the vnode_management_timer? See verify_dt_converge for an example.

Sean Cribbs

**Comment by beerriot** [comment]
Just tried it. Unfortunately, it increases the likelihood that handoff will happen before the cluster has downgraded the fold req version, preventing the test from triggering the behavior it's intended to test.

**Comment by beerriot** [comment]
Oh, hey - `vnode_management_timer` can be changed on the fly. I've just submitted a patch to lower it _after_ we've confirmed that the fold req version has been renegotiated: basho/riak_test#409
